//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklepy.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UzytkownicyEntities : DbContext
    {
        public UzytkownicyEntities()
            : base("name=UzytkownicyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Klient_has_Sklep> Klient_has_Sklep { get; set; }
        public virtual DbSet<LOOKUPRole> LOOKUPRoles { get; set; }
        public virtual DbSet<Miejsce> Miejsces { get; set; }
        public virtual DbSet<Produkt> Produkts { get; set; }
        public virtual DbSet<RodzajProd> RodzajProds { get; set; }
        public virtual DbSet<Sklep> Skleps { get; set; }
        public virtual DbSet<Sklep_has_Miejsce> Sklep_has_Miejsce { get; set; }
        public virtual DbSet<Sklep_has_Produkt> Sklep_has_Produkt { get; set; }
        public virtual DbSet<SYSUser> SYSUsers { get; set; }
        public virtual DbSet<SYSUserProfile> SYSUserProfiles { get; set; }
        public virtual DbSet<SYSUserRole> SYSUserRoles { get; set; }
        public virtual DbSet<SzczProd> SzczProds { get; set; }
    }
}
