//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklepy.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Sklep_has_Produkt = new HashSet<Sklep_has_Produkt>();
            this.SzczProds = new HashSet<SzczProd>();
        }
    
        public int ProduktID { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IloscOgolem { get; set; }
        public Nullable<double> Cena { get; set; }
        public int RodzajProdID { get; set; }
    
        public virtual RodzajProd RodzajProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklep_has_Produkt> Sklep_has_Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzczProd> SzczProds { get; set; }
    }
}
